### ISSUE TITLE
content_size() broken

### ISSUE THREAD

**Issue by Code7R** [TexZK/bytesparse#17]
While porting some code from hexrec.blocks to bytesparse, stumbled upon following. `wtf.bin` is just some random data.

```
>>> import bytesparse
>>> import hexrec.records as hr
>>> tmp = bytesparse.Memory.from_blocks(hr.load_blocks("/tmp/wtf.bin"))
>>> tmp.content_size()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
```

**Comment by TexZK** [comment]
Nice to see you're playing with it.
What you've found isn't a bug: `bytesparse.Memory.content_size` is a _Python property_, so you should access to it as if it were a normal attribute:

```py
>>> import bytesparse
>>> tmp = bytesparse.Memory.from_bytes(b'Hello, World!', 0x1234
>>> type(tmp.content_size)
<class 'int'>
>>> tmp.content_size
13
```

**Comment by Code7R** [comment]
Is it? Let's see:

```
    @ImmutableMemory.content_size.getter
    def content_size(
        self,
    ) -> Address:

        return sum(len(block_data) for _, block_data in self._blocks)

```

That looks like your code with your documentation.

And yeah, I am playing with it. Since you wish to supersede hexrec.blocks, I am trying to port a real world application to ` bytesparse` and see to report all issues (and sometimes user=stupid type inconveniences) along the way.

**Comment by TexZK** [comment]
Thank you for your effort, I really appreciate your help. I already use the library for simple tasks at work, but I also need some public feedbacks to steer to the right direction.

Since this is made on my spare time, some lesser features might not be well documented.
Otherwise, please check the documentation, as most of it should also display usage examples.
